# Usar una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo package.json y package-lock.json
COPY src/package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el código de la aplicación
COPY src .

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 3001

# Comando para ejecutar la aplicación
CMD ["npm", "start"]